project_name: lot
release:
  github:
    owner: infracloudio
    name: lot
  name_template: '{{.Tag}}'
before:
builds:
- id: lot
  binary: lot
  main: main.go
  ldflags: -s -w -extldflags -static
  env: &env
  - GO111MODULE=on
  goos:
  - linux
  goarch: &goarch
  - amd64

archive:
  format: tar.gz
  name_template: '{{ .Binary }}_{{ .Version }}_{{ .Arch }}'
  files:
  - licence*
  - LICENCE*
  - readme*
  - README*
  - changelog*
  - CHANGELOG*

snapshot:
  name_template: '{{ .Tag }}'
checksum:
  name_template: 'checksums.txt'
changelog:
  sort: asc
  filters:
    exclude:
    - '^docs:'
    - '^test:'
